### PR TITLE
made basic function for git practising - Mo/Matt

### PR DESCRIPTION
**Pull request by MoJama1995**
review this pls

### CODE REVIEW

**Review by JoshKain — CHANGES_REQUESTED** [review]
.gitignore please

**Review by samuellea — CHANGES_REQUESTED** [review]
Please add node_modules to the .gitignore! 😨😨😨

**Review by KellyUK — CHANGES_REQUESTED** [review]
Please git ignore the node modules

**Review by JoshKain — APPROVED** [review]

**Review by KellyUK — APPROVED** [review]

**Review by samuellea — APPROVED** [review]
Looks good, m9

**Review by tuskemx — APPROVED** [review]

**Review by tuskemx — APPROVED** [review]

**Pull request merged**
